import { shortcutPaths } from './shortcuts.js';
import { unlinkSync, realpathSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { parse as toml } from 'smol-toml';
import { parse as jsonc, modify, applyEdits } from 'jsonc-parser';
import type { ParseError } from 'jsonc-parser';
import { z } from 'zod';
import { atomicWrite, readText } from './fs.js';
import { ensure, hash } from './model.js';
import type { Agent } from './model.js';
import type { Store } from './store.js';

const record = z.record(z.string(), z.unknown());
type Edit = { path: string; before: string; after: string | null };
function strip(text: string, begin: string, end: string): string {
  const start = text.indexOf(begin),
    stop = text.indexOf(end);
  if (start < 0 && stop < 0) return text;
  ensure(
    start >= 0 && stop > start && text.split(begin).length === 2 && text.split(end).length === 2,
    'Malformed Co-memo markers; repair manually before disconnecting',
  );
  return text.slice(0, start) + text.slice(stop + end.length);
}
/** Preview reads configuration only: no store creation, migration or synchronization. */
export function planDisconnect(directory: string, agent: Agent) {
  const root = realpathSync(directory);
  const edits: Edit[] = [];
  const edit = (relative: string, change: (text: string) => string | null) => {
    const path = join(root, relative),
      before = readText(path);
    if (before === null) return;
    const after = change(before);
    if (before !== after) edits.push({ path, before, after });
  };
  edit(agent === 'claude' ? 'CLAUDE.local.md' : 'AGENTS.md', (text) =>
    strip(text, `<!-- co-memo:adapter-${agent}:start -->`, `<!-- co-memo:adapter-${agent}:end -->`),
  );
  if (agent === 'claude' || agent === 'codex') {
    edit(agent === 'claude' ? '.claude/settings.local.json' : '.codex/hooks.json', (text) => {
      const doc = record.parse(JSON.parse(text));
      const hooks = record.parse(doc.hooks ?? {});
      let changed = false;
      for (const event of ['SessionStart', 'UserPromptSubmit', 'Stop']) {
        if (hooks[event] === undefined) continue;
        const groups = z.array(record).parse(hooks[event]);
        hooks[event] = groups.flatMap((group) => {
          const entries = z.array(record).parse(group.hooks);
          const retained = entries.filter(
            (h) =>
              !(typeof h.command === 'string' && h.command.endsWith(` # co-memo:managed:${event}`)),
          );
          if (retained.length === entries.length) return [group];
          changed = true;
          return retained.length ? [{ ...group, hooks: retained }] : [];
        });
      }
      if (!changed) return text;
      doc.hooks = hooks;
      return JSON.stringify(doc, null, 2) + '\n';
    });
  }
  if (agent === 'codex')
    edit('.codex/config.toml', (text) => {
      toml(text);
      const after = strip(text, '# co-memo:mcp:start', '# co-memo:mcp:end');
      const outside = record.parse(toml(after));
      ensure(
        record.parse(outside.mcp_servers ?? {})['co-memo'] === undefined,
        'Unmanaged co-memo MCP entry; refusing disconnect',
      );
      return after;
    });
  const removeJson = (relative: string, paths: string[][], strict = false) =>
    edit(relative, (text) => {
      if (strict) JSON.parse(text);
      const errors: ParseError[] = [];
      const doc = record.parse(jsonc(text, errors, { allowTrailingComma: true }));
      ensure(!errors.length, 'Malformed MCP configuration');
      let after = text;
      for (const path of paths) {
        let parent = doc;
        for (const key of path.slice(0, -1)) parent = record.parse(parent[key] ?? {});
        const entry = parent[path.at(-1)!];
        if (entry === undefined) continue;
        const data = record.parse(entry);
        const args = Array.isArray(data.args) ? data.args : data.command;
        ensure(
          Array.isArray(args) && args.includes('--co-memo-managed'),
          'Unmanaged co-memo MCP entry; refusing disconnect',
        );
        after = applyEdits(after, modify(after, path, undefined, {}));
      }
      return after;
    });
  if (agent === 'claude') removeJson('.mcp.json', [['mcpServers', 'co-memo']], true);
  if (agent === 'opencode') {
    for (const path of ['opencode.json', 'opencode.jsonc'])
      removeJson(path, [
        ['mcp', 'co-memo'],
        ['mcp', 'servers', 'co-memo'],
      ]);
  }
  const owned = (relative: string, marker: string) =>
    edit(relative, (text) => {
      ensure(text.startsWith(marker), `Unmanaged file: ${relative}; refusing disconnect`);
      return null;
    });
  if (agent === 'pi') owned('.pi/extensions/co-memo.ts', '// Generated by Co-memo.');
  if (agent === 'opencode') {
    owned('.opencode/plugins/co-memo.ts', '// Generated by Co-memo.');
    edit('.opencode/commands/co-memo.md', (text) => {
      ensure(
        text.includes('<!-- Generated by Co-memo. -->'),
        'Unmanaged Co-memo command; refusing disconnect',
      );
      return null;
    });
  }
  const skillRoot = { claude: '.claude', codex: '.agents', pi: '.pi', opencode: '.opencode' }[
    agent
  ];
  for (const shortcut of shortcutPaths(agent)) {
    edit(`${skillRoot}/${shortcut.path}`, (text) => {
      ensure(
        text.includes('<!-- Generated by Co-memo. -->'),
        'Unmanaged Co-memo shortcut; refusing disconnect',
      );
      return null;
    });
  }
  edit(`${skillRoot}/skills/co-memo/SKILL.md`, (text) => {
    ensure(
      text.includes('<!-- Generated by Co-memo. -->'),
      'Unmanaged Co-memo skill; refusing disconnect',
    );
    return null;
  });
  return { root, agent, edits };
}
export function describeDisconnect(plan: ReturnType<typeof planDisconnect>) {
  return {
    applied: false,
    root: plan.root,
    agent: plan.agent,
    changes: plan.edits.map((e) => ({
      path: e.path,
      action: e.after === null ? 'archive-and-remove' : 'update',
    })),
    memory:
      'Central memories are retained. The local projection is archived without importing pending edits; synchronization for this replica stops.',
    next: 'Close this agent before applying. Restart it afterward; existing sessions cannot be unloaded remotely.',
  };
}
export function applyDisconnect(store: Store, plan: ReturnType<typeof planDisconnect>) {
  const replica = store
    .replicas()
    .find(
      (r) => r.agent === plan.agent && r.path === join(plan.root, '.co-memo', `${plan.agent}.md`),
    );
  const edits = [...plan.edits];
  if (replica) {
    const text = readText(replica.path);
    if (text !== null) edits.push({ path: replica.path, before: text, after: null });
  }
  for (const edit of edits)
    ensure(
      readText(edit.path) === edit.before,
      `Configuration changed since preview: ${edit.path}`,
    );
  const archive = join(store.home, 'disconnected', randomUUID());
  // Save exact originals before any removal. No memory ingestion or central-note deletion.
  for (const [index, edit] of edits.entries())
    atomicWrite(join(archive, `${index}.txt`), edit.before, null);
  if (edits.length)
    atomicWrite(
      join(archive, 'manifest.json'),
      JSON.stringify(
        edits.map((e, index) => ({ original: e.path, backup: `${index}.txt` })),
        null,
        2,
      ),
      null,
    );
  for (const edit of edits) {
    if (edit.after === null) {
      ensure(readText(edit.path) === edit.before, `File changed during disconnect: ${edit.path}`);
      unlinkSync(edit.path);
    } else atomicWrite(edit.path, edit.after, hash(edit.before));
  }
  if (replica)
    store.transaction(() => store.db.prepare('DELETE FROM replicas WHERE id=?').run(replica.id));
  return {
    applied: true,
    status: 'disconnected',
    agent: plan.agent,
    archive: edits.length ? archive : null,
    centralMemories: 'retained',
    hostUnloaded: false,
    next: 'Restart the agent to unload its tools/hooks. The archived projection is no longer synchronized. Gitignore entries are retained to protect local configuration and memories.',
  };
}
