/** Self-contained host plugins: SQLite always runs in the pinned Node process, not Bun. */
export function openCodePlugin(executable: string, argv: string[], api: 'v1' | 'v2'): string {
  const shared = `// Generated by Co-memo. Re-run connect opencode after moving the installation.
// OpenCode API: ${api}
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
async function run(event: string): Promise<string> {
  try {
    const { stdout } = await exec(${JSON.stringify(executable)}, [...${JSON.stringify(argv)}, 'bridge', '--agent', 'opencode', '--event', event], { timeout: 15000, maxBuffer: 1024 * 1024 });
    const result = JSON.parse(stdout);
    if (result.errors.length || result.conflicts.length) console.warn('Co-memo needs attention: run co-memo status or conflicts.');
    return result.context;
  } catch (error) {
    console.warn('Co-memo sync failed:', error);
    return 'Co-memo memory is unavailable. Do not assume earlier shared notes are current; run co-memo status.';
  }
}
`;
  if (api === 'v1')
    return (
      shared +
      `
export default async function () {
  return {
    'experimental.chat.system.transform': async (_input: unknown, output: { system: string[] }) => {
      output.system.push(await run('context'));
    },
    'tool.execute.after': async () => { await run('tool_after'); },
    event: async ({ event }: { event: { type: string } }) => {
      if (event.type === 'session.idle') await run('idle');
    },
  };
}
`
    );
  // @opencode/plugin 2.0.12 Plugin.define is an identity function; exporting its
  // structural definition avoids installing SDK dependencies in the user's project.
  return (
    shared +
    `
type Context = {
  session: { hook(name: 'context', callback: (event: { system: { type: 'text'; text: string }[] }) => Promise<void>): Promise<unknown> };
  tool: { hook(name: 'execute.after', callback: () => Promise<void>): Promise<unknown> };
};
export default {
  id: 'co-memo',
  async setup(ctx: Context) {
    await ctx.session.hook('context', async (event) => {
      event.system.push({ type: 'text', text: await run('context') });
    });
    await ctx.tool.hook('execute.after', async () => { await run('tool_after'); });
  },
};
`
  );
}
