import { realpathSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseToml } from 'smol-toml';
import { parse as parseJsonc, modify, applyEdits } from 'jsonc-parser';
import type { ParseError } from 'jsonc-parser';
import { z } from 'zod';
import { prepareAdapter } from './adapters.js';
import type { Edit } from './adapters.js';
import { readText } from './fs.js';
import { ensure } from './model.js';
import type { Agent } from './model.js';

const record = z.record(z.string(), z.unknown());
const marker = '<!-- Generated by Co-memo. -->';
function jsonConfig(original: string, keys: string[], value: unknown): string {
  const errors: ParseError[] = [];
  const text = original.trim() ? original : '{}\n';
  const doc = record.parse(parseJsonc(text, errors, { allowTrailingComma: true }));
  ensure(errors.length === 0, 'Malformed MCP JSON/JSONC configuration');
  let servers = doc;
  for (const key of keys) servers = record.parse(servers[key] ?? {});
  const existing = servers['co-memo'];
  if (existing !== undefined) {
    const entry = record.parse(existing);
    const args = Array.isArray(entry.args) ? entry.args : entry.command;
    ensure(
      Array.isArray(args) && args.includes('--co-memo-managed'),
      'Existing co-memo MCP entry is not managed by Co-memo',
    );
  }
  return applyEdits(
    text,
    modify(text, [...keys, 'co-memo'], value, {
      formattingOptions: { insertSpaces: true, tabSize: 2, eol: '\n' },
    }),
  );
}
function tomlConfig(original: string, executable: string, args: string[]): string {
  const begin = '# co-memo:mcp:start',
    end = '# co-memo:mcp:end';
  const start = original.indexOf(begin),
    stop = original.indexOf(end);
  ensure(
    (start === -1 && stop === -1) ||
      (start >= 0 &&
        stop > start &&
        original.split(begin).length === 2 &&
        original.split(end).length === 2),
    'Malformed Co-memo TOML markers',
  );
  // Validate the whole file before replacing a managed section, then check collisions outside it.
  parseToml(original);
  const outside =
    start < 0
      ? original
      : original.slice(0, start) + original.slice(stop + end.length).replace(/^\r?\n/, '');
  const parsed = record.parse(parseToml(outside));
  const servers = record.parse(parsed.mcp_servers ?? {});
  ensure(servers['co-memo'] === undefined, 'Existing co-memo MCP entry is not managed by Co-memo');
  const block = `${begin}\n[mcp_servers.co-memo]\ncommand = ${JSON.stringify(executable)}\nargs = ${JSON.stringify(args)}\n${end}\n`;
  const result =
    start < 0
      ? outside + (outside.endsWith('\n') || !outside ? '' : '\n') + block
      : original.slice(0, start) + block + original.slice(stop + end.length).replace(/^\r?\n/, '');
  parseToml(result);
  return result;
}
export function prepareSetup(
  root: string,
  agent: Agent,
  home: string,
  options: { toolsOnly?: boolean; opencodeApi?: 'v1' | 'v2' },
): Edit[] {
  const existingPlugin =
    agent === 'opencode' ? readText(join(root, '.opencode/plugins/co-memo.ts')) : null;
  const existingConfig =
    agent === 'opencode'
      ? (readText(join(root, 'opencode.jsonc')) ?? readText(join(root, 'opencode.json')))
      : null;
  const configMcp = existingConfig ? parseJsonc(existingConfig)?.mcp : undefined;
  const api =
    options.opencodeApi ??
    (existingPlugin?.includes('// OpenCode API: v2') || (!existingPlugin && configMcp?.servers)
      ? 'v2'
      : 'v1');
  const edits = prepareAdapter(root, agent, home, api, !options.toolsOnly);
  const executable = realpathSync(process.execPath);
  const cli = realpathSync(fileURLToPath(new URL('./cli.js', import.meta.url)));
  const args = [cli, '--home', home, '--project', root, 'serve', '--co-memo-managed'];
  const prepare = (relative: string, update: (text: string) => string) => {
    const path = join(root, relative),
      before = readText(path);
    edits.push({ path, before, after: update(before ?? '') });
  };
  let configPath: string | null = null;
  if (agent === 'codex') {
    configPath = '.codex/config.toml';
    prepare(configPath, (text) => tomlConfig(text, executable, args));
  } else if (agent === 'claude') {
    configPath = '.mcp.json';
    prepare(configPath, (text) => {
      if (text.trim()) record.parse(JSON.parse(text));
      return jsonConfig(text, ['mcpServers'], { type: 'stdio', command: executable, args });
    });
  } else if (agent === 'opencode') {
    const json = readText(join(root, 'opencode.json'));
    const jsonc = readText(join(root, 'opencode.jsonc'));
    ensure(
      json === null || jsonc === null,
      'Both opencode.json and opencode.jsonc exist; consolidate them before setup',
    );
    configPath = jsonc !== null ? 'opencode.jsonc' : 'opencode.json';
    prepare(configPath, (text) => {
      const errors: ParseError[] = [];
      const doc = record.parse(
        parseJsonc(text.trim() ? text : '{}', errors, { allowTrailingComma: true }),
      );
      ensure(errors.length === 0, 'Malformed OpenCode configuration');
      const mcp = record.parse(doc.mcp ?? {});
      const keys = api === 'v2' ? ['mcp', 'servers'] : ['mcp'];
      const value =
        api === 'v2'
          ? { type: 'local', command: [executable, ...args] }
          : { type: 'local', command: [executable, ...args], enabled: true };
      if (api === 'v2') {
        ensure(
          Object.keys(mcp).every((k) => k === 'servers' || k === 'co-memo'),
          'Migrate other OpenCode V1 MCP entries to mcp.servers before selecting V2',
        );
        if (mcp['co-memo'] !== undefined) {
          jsonConfig(text, ['mcp'], value); // Ownership validation before removing the old managed entry.
          text = applyEdits(text, modify(text, ['mcp', 'co-memo'], undefined, {}));
        }
      } else if (mcp.servers !== undefined) {
        const servers = record.parse(mcp.servers);
        ensure(
          Object.keys(servers).every((k) => k === 'co-memo'),
          'Migrate other OpenCode V2 MCP entries before selecting V1',
        );
        if (servers['co-memo'] !== undefined) jsonConfig(text, ['mcp', 'servers'], value);
        text = applyEdits(text, modify(text, ['mcp', 'servers'], undefined, {}));
      }
      return jsonConfig(text, keys, value);
    });
  }
  const skillRoot = { codex: '.agents', claude: '.claude', pi: '.pi', opencode: '.opencode' }[
    agent
  ];
  const skillPath = `${skillRoot}/skills/co-memo/SKILL.md`;
  const skill = readFileSync(new URL('../skills/co-memo/SKILL.md', import.meta.url), 'utf8');
  prepare(skillPath, (text) => {
    ensure(!text || text.includes(marker), 'Existing co-memo skill is not managed by Co-memo');
    return skill;
  });
  const ignore = edits.find((e) => e.path === join(root, '.gitignore'))!;
  for (const path of [configPath, skillPath]) {
    if (path && !ignore.after.split(/\r?\n/).includes('/' + path))
      ignore.after += '/' + path + '\n';
  }
  return edits;
}
