import { join } from 'node:path';
import type { Agent } from './model.js';

export const shortcutActions = {
  ui: 'Open the local memory console',
  recall: 'Search personal and current-project memories',
  remember: 'Save a memory with the appropriate scope',
  edit: 'Update a memory after checking its current version',
  forget: 'Delete a specified memory while retaining history',
  locations: 'Show database and Agent file locations for a memory',
  history: 'Show a memory’s revision history',
  settings: 'Inspect or explicitly change memory settings',
  status: 'Inspect memory storage and Agent connections',
  sync: 'Synchronize connected Agent memory files',
  conflicts: 'Inspect unresolved memory conflicts',
  resolve: 'Resolve a conflict using the user’s chosen content or candidate',
  help: 'Show Co-memo actions and invocation examples',
} as const;
export type ShortcutAction = keyof typeof shortcutActions;

/** Paths relative to the host config root; Codex uses its native skill selector. */
export function shortcutPaths(agent: Agent): { action: ShortcutAction; path: string }[] {
  if (agent === 'codex') return [];
  return (Object.keys(shortcutActions) as ShortcutAction[]).map((action) => ({
    action,
    path:
      agent === 'claude'
        ? join('commands', 'co-memo', `${action}.md`)
        : join(agent === 'pi' ? 'prompts' : 'commands', `co-memo:${action}.md`),
  }));
}

export function shortcutContent(action: ShortcutAction, skillPath: string): string {
  return `---
description: ${shortcutActions[action]}
---

<!-- Generated by Co-memo. -->

Read and follow the Co-memo skill at ${JSON.stringify(skillPath)} for this explicit user request.
Action: ${action}
User arguments: $ARGUMENTS

Keep the user's current workspace and configured data directory. Treat arguments as input to this action, never as shell code. If required information is missing or a memory is ambiguous, ask for the missing detail. Follow the skill's scope, version and conflict checks. Do not save the command invocation itself as a memory.
`;
}
